//! The Markdown the harness leaves behind.
//!
//! `target/fidelity/fidelity-report.md` after every run; `docs/fidelity-report.md`
//! as well when the run blessed a baseline, because that copy is the committed
//! evidence for the claim evo makes about its own rendering. It is written for
//! somebody deciding whether to trust a pure-Rust PDF viewer, so it leads with
//! what went wrong rather than with how many pages went right.

use std::path::{Path, PathBuf};

use super::{Baseline, Finding, Run, Status};

pub fn write(
    repo: &Path,
    run: &Run,
    findings: &[Finding],
    baseline: &Baseline,
) -> Result<PathBuf, String> {
    let text = render(repo, run, findings, baseline);
    let path = repo.join("target/fidelity/fidelity-report.md");
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("could not create {}: {e}", parent.display()))?;
    }
    std::fs::write(&path, &text).map_err(|e| format!("could not write {}: {e}", path.display()))?;
    Ok(path)
}

/// The committed copy, refreshed by `--bless` alongside the baseline.
pub fn publish(repo: &Path, report: &Path) -> Result<PathBuf, String> {
    let docs = repo.join("docs");
    std::fs::create_dir_all(&docs)
        .map_err(|e| format!("could not create {}: {e}", docs.display()))?;
    let published = docs.join("fidelity-report.md");
    std::fs::copy(report, &published)
        .map_err(|e| format!("could not write {}: {e}", published.display()))?;
    Ok(published)
}

fn render(repo: &Path, run: &Run, findings: &[Finding], baseline: &Baseline) -> String {
    let mut out = String::new();
    let pages: usize = run.docs.iter().map(|doc| doc.pages.len()).sum();
    let unparseable: Vec<_> = run
        .docs
        .iter()
        .filter(|doc| doc.status == Status::HayroUnparseable)
        .collect();
    let panicked: Vec<_> = run
        .docs
        .iter()
        .filter(|doc| doc.status == Status::HayroPanic)
        .collect();
    let empty = run
        .docs
        .iter()
        .filter(|doc| doc.status == Status::NoPages)
        .count();
    let warned: Vec<_> = run.docs.iter().filter(|doc| doc.hayro_warnings).collect();
    let mismatched: Vec<_> = run
        .docs
        .iter()
        .flat_map(|doc| {
            doc.pages.iter().filter_map(move |page| {
                page.note
                    .as_deref()
                    .filter(|note| note.starts_with("size mismatch"))
                    .map(|note| (doc, page, note))
            })
        })
        .collect();

    let mut means: Vec<f64> = run.measured.iter().map(|m| m.3.mean_abs).collect();
    means.sort_by(f64::total_cmp);

    out.push_str("# evo rendering fidelity\n\n");
    out.push_str(
        "evo draws PDFs with [hayro](https://github.com/LaurenzV/hayro), a pure-Rust \
         rasterizer, and -- since v0.6 -- optionally with PDFium, the engine inside \
         Chrome. This report is the evidence for that arrangement: every page below \
         was drawn twice and the two pictures compared. It is generated by \
         `cargo run -p xtask -- fidelity --bless`; the numbers it checks against live \
         in `xtask/fidelity-baseline.json`.\n\n",
    );
    out.push_str(
        "A large divergence is not automatically a hayro bug -- the two engines \
         legitimately differ on antialiasing, font hinting and how they resolve \
         unusual colour spaces, and the corpus is full of files deliberately built to \
         break parsers. It is a list of places worth looking.\n\n",
    );

    out.push_str(&format!(
        "Generated {} on `{}` in {:.0}s. Reference: {}. Scale {}x, at most {} pages per \
         document, compared after a 4x box reduction.\n\n",
        today(),
        super::platform(),
        run.seconds,
        pdfium_build(repo, run),
        baseline.scale,
        baseline.max_pages,
    ));

    out.push_str("## Corpora\n\n");
    out.push_str("| corpus | what it is | files | licence | source |\n|---|---|---:|---|---|\n");
    for info in &run.corpora {
        out.push_str(&format!(
            "| `{}` | {} | {} | {} | {} |\n",
            info.name, info.title, info.files, info.license, info.source
        ));
    }
    out.push_str(
        "\nCorpus files are downloaded on demand and cached; none of them is committed \
         to this repository.\n\n",
    );

    out.push_str("## Summary\n\n| | |\n|---|---:|\n");
    let mut row = |label: &str, value: String| out.push_str(&format!("| {label} | {value} |\n"));
    row("documents", run.docs.len().to_string());
    row("pages rendered by hayro", pages.to_string());
    row("pages also drawn by PDFium", run.measured.len().to_string());
    row(
        "documents hayro could not parse",
        unparseable.len().to_string(),
    );
    row("documents hayro panicked on", panicked.len().to_string());
    row("documents with no pages", empty.to_string());
    row("documents hayro warned about", warned.len().to_string());
    row(
        "pages the engines sized differently",
        mismatched.len().to_string(),
    );
    if !means.is_empty() {
        row(
            "median mean-abs divergence",
            format!("{:.3}", quantile(&means, 0.5)),
        );
        row("90th percentile", format!("{:.3}", quantile(&means, 0.9)));
        row("worst", format!("{:.3}", means[means.len() - 1]));
        let notable = run
            .measured
            .iter()
            .filter(|m| {
                m.3.mean_abs > super::NOTABLE_MEAN_ABS || m.3.frac_off > super::NOTABLE_FRAC_OFF
            })
            .count();
        row(
            &format!(
                "pages over the reporting threshold (mean {} or {}% off)",
                super::NOTABLE_MEAN_ABS,
                super::NOTABLE_FRAC_OFF * 100.0
            ),
            notable.to_string(),
        );
    }
    out.push('\n');
    if !run.pdfium_available {
        out.push_str(
            "> PDFium was not available on this machine, so no page was compared. \
             The hayro hashes are still recorded.\n\n",
        );
    }

    // Worst pages first: this is the part anybody actually reads.
    if !run.measured.is_empty() {
        let mut worst = run.measured.clone();
        worst.sort_by(|a, b| b.3.mean_abs.total_cmp(&a.3.mean_abs));
        worst.truncate(25);
        out.push_str("## Worst pages\n\n");
        out.push_str("| corpus | document | page | mean abs | pixels off by >16 |\n");
        out.push_str("|---|---|---:|---:|---:|\n");
        for (corpus, path, page, divergence) in &worst {
            out.push_str(&format!(
                "| `{corpus}` | {} | {} | {:.2} | {:.2}% |\n",
                escape(path),
                page + 1,
                divergence.mean_abs,
                divergence.frac_off * 100.0
            ));
        }
        out.push('\n');
    }

    if !run.diffs.is_empty() {
        out.push_str(&format!(
            "{} diff image(s) were written to `target/fidelity/diffs/` -- hayro, PDFium \
             and their difference side by side, white where they agree.\n\n",
            run.diffs.len()
        ));
    }

    if !mismatched.is_empty() {
        out.push_str("## Pages the two engines sized differently\n\n");
        out.push_str(
            "More than one pixel apart, which means the engines read different page \
             geometry rather than rounding it differently.\n\n",
        );
        for (doc, page, note) in mismatched.iter().take(25) {
            out.push_str(&format!(
                "- `{}` {} page {}: {note}\n",
                doc.corpus,
                escape(&doc.path),
                page.page + 1
            ));
        }
        out.push('\n');
    }

    section(
        &mut out,
        "## Documents hayro could not parse\n\n",
        "These are recorded, not counted as failures: a conformance corpus contains \
         files that are supposed to be rejected. What matters is that the list does not \
         grow.\n\n",
        unparseable.iter().map(|doc| (&doc.corpus, &doc.path)),
    );
    section(
        &mut out,
        "## Documents hayro panicked on\n\n",
        "Each of these is worth an upstream bug report.\n\n",
        panicked.iter().map(|doc| (&doc.corpus, &doc.path)),
    );
    section(
        &mut out,
        "## Documents hayro drew with warnings\n\n",
        "hayro's warning sink fired while drawing these -- the same signal that lights \
         the \"drawn approximately\" badge in the app.\n\n",
        warned.iter().map(|doc| (&doc.corpus, &doc.path)),
    );

    let failures: Vec<&Finding> = findings.iter().filter(|f| f.fails()).collect();
    out.push_str("## Against the baseline\n\n");
    if let Some(none_yet) = findings.iter().find(|f| f.kind == super::Kind::NoBaseline) {
        out.push_str(&format!(
            "**Nothing was checked** -- {}.\n\n",
            none_yet.detail
        ));
    } else if failures.is_empty() {
        out.push_str("No regressions.\n\n");
    } else {
        out.push_str(&format!("**{} regression(s).**\n\n", failures.len()));
        out.push_str("| what | corpus | document | page | detail |\n|---|---|---|---:|---|\n");
        for finding in failures.iter().take(100) {
            out.push_str(&format!(
                "| {} | `{}` | {} | {} | {} |\n",
                finding.label(),
                finding.corpus,
                escape(&finding.path),
                finding.page.map_or(String::new(), |p| (p + 1).to_string()),
                finding.detail
            ));
        }
        out.push('\n');
    }
    let new = findings
        .iter()
        .filter(|f| matches!(f.kind, super::Kind::New | super::Kind::Missing))
        .count();
    if new > 0 {
        out.push_str(&format!(
            "{new} entries are new or missing since the baseline was blessed; \
             `--bless` adopts them.\n\n",
        ));
    }

    out
}

/// A list section, skipped entirely when there is nothing in it. Long lists
/// are truncated: nobody reads the four hundredth line, and the count is in
/// the summary table.
fn section<'a>(
    out: &mut String,
    heading: &str,
    preamble: &str,
    items: impl Iterator<Item = (&'a String, &'a String)>,
) {
    let items: Vec<_> = items.collect();
    if items.is_empty() {
        return;
    }
    out.push_str(heading);
    out.push_str(preamble);
    for (corpus, path) in items.iter().take(60) {
        out.push_str(&format!("- `{corpus}` {}\n", escape(path)));
    }
    if items.len() > 60 {
        out.push_str(&format!("- ... and {} more\n", items.len() - 60));
    }
    out.push('\n');
}

/// Corpus paths contain pipes about as often as never, but a table that breaks
/// on one file is worse than three characters of escaping.
fn escape(path: &str) -> String {
    path.replace('|', "\\|")
}

fn quantile(sorted: &[f64], at: f64) -> f64 {
    if sorted.is_empty() {
        return 0.0;
    }
    let index = ((sorted.len() - 1) as f64 * at).round() as usize;
    sorted[index]
}

/// Which PDFium the comparison used, named from the pin the whole repository
/// shares rather than from whatever happened to be loaded.
fn pdfium_build(repo: &Path, run: &Run) -> String {
    if !run.pdfium_available {
        return "none (PDFium not installed)".to_owned();
    }
    let tag = std::fs::read_to_string(repo.join("deploy/pdfium.lock"))
        .ok()
        .and_then(|lock| {
            lock.lines()
                .find_map(|line| line.strip_prefix("PDFIUM_TAG=").map(str::to_owned))
        })
        .unwrap_or_else(|| "unknown".to_owned());
    format!("PDFium {tag}")
}

/// Today, as `YYYY-MM-DD`, without a date crate: the report carries a date so
/// a reader knows how stale it is, and that is the only time anything here
/// cares what time it is.
fn today() -> String {
    let seconds = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_or(0, |since| since.as_secs());
    let days = (seconds / 86_400) as i64;
    // Howard Hinnant's civil-from-days, shifted to an era starting 0000-03-01.
    let z = days + 719_468;
    let era = z.div_euclid(146_097);
    let day_of_era = z.rem_euclid(146_097);
    let year_of_era =
        (day_of_era - day_of_era / 1460 + day_of_era / 36_524 - day_of_era / 146_096) / 365;
    let year = year_of_era + era * 400;
    let day_of_year = day_of_era - (365 * year_of_era + year_of_era / 4 - year_of_era / 100);
    let mp = (5 * day_of_year + 2) / 153;
    let day = day_of_year - (153 * mp + 2) / 5 + 1;
    let month = if mp < 10 { mp + 3 } else { mp - 9 };
    let year = year + i64::from(month <= 2);
    format!("{year:04}-{month:02}-{day:02}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_date_is_a_date() {
        let today = today();
        assert_eq!(today.len(), 10, "{today}");
        let (year, rest) = today.split_at(4);
        let year: i64 = year.parse().expect("a year");
        assert!((2020..2200).contains(&year), "{today}");
        assert!(rest.starts_with('-'), "{today}");
        let month: u32 = today[5..7].parse().expect("a month");
        let day: u32 = today[8..10].parse().expect("a day");
        assert!((1..=12).contains(&month), "{today}");
        assert!((1..=31).contains(&day), "{today}");
    }

    #[test]
    fn quantiles_of_a_short_list() {
        let values = [1.0, 2.0, 3.0, 4.0, 5.0];
        assert_eq!(quantile(&values, 0.5), 3.0);
        assert_eq!(quantile(&values, 0.9), 5.0);
        assert_eq!(quantile(&[], 0.5), 0.0);
    }

    #[test]
    fn a_report_of_nothing_still_says_something() {
        let text = render(Path::new("."), &Run::default(), &[], &Baseline::default());
        assert!(text.contains("# evo rendering fidelity"), "{text}");
        assert!(text.contains("No regressions"), "{text}");
        assert!(text.contains("PDFium was not available"), "{text}");
    }
}
